development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: homework_development
  pool: 5
  username: <%= ENV["HOMEWORK_DATABASE_USERNAME"] %>
  password: <%= ENV["HOMEWORK_DATABASE_PASSWORD"] %>

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: homework_test
  pool: 5
  username: <%= ENV["HOMEWORK_DATABASE_USERNAME"] %>
  password: <%= ENV["HOMEWORK_DATABASE_PASSWORD"] %>

production:
  adapter: postgresql
  host: ec2-44-210-36-247.compute-1.amazonaws.com
  encoding: unicode
  database: ec2-44-210-36-247.compute-1.amazonaws.com
  pool: 5
  username: eftqhpfdulwcgg
  password: 247e531d8287b955ada7cfb44c6dbff2380143510cbaed6c43e3b10ea982d90e
