development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: homework_development
  pool: 5
  username: <%= ENV["HOMEWORK_DATABASE_USERNAME"] %>
  password: <%= ENV["HOMEWORK_DATABASE_PASSWORD"] %>

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: homework_test
  pool: 5
  username: <%= ENV["HOMEWORK_DATABASE_USERNAME"] %>
  password: <%= ENV["HOMEWORK_DATABASE_PASSWORD"] %>

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: homework_production
  pool: 5
  username: <%= ENV["HOMEWORK_DATABASE_USERNAME"] %>
  password: <%= ENV["HOMEWORK_DATABASE_PASSWORD"] %>
